/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MarketsRouteImport } from './routes/markets'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as MarketMarketIdRouteImport } from './routes/market.$marketId'
import { Route as ProfileUsernameRouteImport } from './routes/profile.$username'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketsRoute = MarketsRouteImport.update({
  id: '/markets',
  path: '/markets',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketMarketIdRoute = MarketMarketIdRouteImport.update({
  id: '/market/$marketId',
  path: '/market/$marketId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileUsernameRoute = ProfileUsernameRouteImport.update({
  id: '/profile/$username',
  path: '/profile/$username',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/markets': typeof MarketsRoute
  '/portfolio': typeof PortfolioRoute
  '/market/$marketId': typeof MarketMarketIdRoute
  '/profile/$username': typeof ProfileUsernameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/markets': typeof MarketsRoute
  '/portfolio': typeof PortfolioRoute
  '/market/$marketId': typeof MarketMarketIdRoute
  '/profile/$username': typeof ProfileUsernameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/markets': typeof MarketsRoute
  '/portfolio': typeof PortfolioRoute
  '/market/$marketId': typeof MarketMarketIdRoute
  '/profile/$username': typeof ProfileUsernameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/markets' | '/portfolio' | '/market/$marketId' | '/profile/$username'
  fileRoutesByTo: FileRoutesByTo
  to:
    '/' | '/markets' | '/portfolio' | '/market/$marketId' | '/profile/$username'
  id:
    | '__root__'
    | '/'
    | '/markets'
    | '/portfolio'
    | '/market/$marketId'
    | '/profile/$username'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MarketsRoute: typeof MarketsRoute
  PortfolioRoute: typeof PortfolioRoute
  MarketMarketIdRoute: typeof MarketMarketIdRoute
  ProfileUsernameRoute: typeof ProfileUsernameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/markets': {
      id: '/markets'
      path: '/markets'
      fullPath: '/markets'
      preLoaderRoute: typeof MarketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market/$marketId': {
      id: '/market/$marketId'
      path: '/market/$marketId'
      fullPath: '/market/$marketId'
      preLoaderRoute: typeof MarketMarketIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$username': {
      id: '/profile/$username'
      path: '/profile/$username'
      fullPath: '/profile/$username'
      preLoaderRoute: typeof ProfileUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MarketsRoute: MarketsRoute,
  PortfolioRoute: PortfolioRoute,
  MarketMarketIdRoute: MarketMarketIdRoute,
  ProfileUsernameRoute: ProfileUsernameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
